PACKAGE_NAME="attack"
PACKAGE_VERSION="0.1.2"
BUILT_MODULE_NAME[0]="tcp_attack"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
